export const CATEGORIES = [
  { id: 'all', name: 'All Games', icon: '🎮', blurb: 'Play thousands of free online games instantly in your browser — no downloads, no installs, no sign-ups. Just click and play across action, puzzle, racing, arcade and dozens more categories.' },
  {
    id: 'action',
    name: 'Action',
    icon: '⚔️',
    description: 'Fast-paced free action games online — fighting, shooting, and adrenaline-fueled challenges you can jump into instantly, no download required.',
    why: 'Free online action games are built for quick reflexes and instant fun — no downloads, no waiting, just fast-paced combat and challenges the moment you click play. Whether you want a five-minute session or a longer run, browser action games let you jump straight into the fight.',
    tips: [
      'Use a keyboard and mouse, or a connected gamepad, for the most responsive controls.',
      'Play in fullscreen mode to stay focused during fast combat sequences.',
      'Start on an easier difficulty to learn enemy patterns before ramping up the challenge.',
    ],
    related: ['shooting', 'adventure'],
  },
  {
    id: 'adventure',
    name: 'Adventure',
    icon: '🗺️',
    description: 'Explore free adventure games online, from story-driven quests to open-world exploration, playable instantly in your browser.',
    why: 'Adventure games reward curiosity — explore maps, solve environmental puzzles, and follow a story at your own pace, all without installing anything. Free browser adventure games are a great pick when you want gameplay with more depth than a quick arcade round.',
    tips: [
      'Keep an eye out for hidden items and interactable objects in each scene.',
      'Save progress often if the game offers checkpoints or auto-save.',
      'Try playing on a larger screen to catch small details in open-world levels.',
    ],
    related: ['action', 'puzzle'],
  },
  {
    id: 'arcade',
    name: 'Arcade',
    icon: '🕹️',
    description: 'Classic and modern free arcade games — quick, addictive gameplay in the browser, no installs needed.',
    why: 'Arcade games are all about pick-up-and-play fun — simple rules, fast rounds, and just-one-more-try replayability. Playing free arcade games online in your browser brings back that classic arcade-cabinet feel without needing any hardware or downloads.',
    tips: [
      'Short sessions work best — arcade games are designed for quick, replayable rounds.',
      'Chase a high score to keep runs competitive against your own best.',
      'Most arcade titles work great on mobile too, so try them on the go.',
    ],
    related: ['hypercasual', 'clicker'],
  },
  {
    id: 'hypercasual',
    name: 'Hypercasual',
    icon: '⚡',
    description: 'Simple, addictive free hypercasual games you can pick up in seconds and play instantly online.',
    why: 'Hypercasual games strip gameplay down to one simple, satisfying mechanic — perfect for a quick break. These free browser games need no tutorial and no download, so you can be playing within seconds of landing on the page.',
    tips: [
      'One-tap or one-swipe controls are common — check the on-screen prompt before starting.',
      'These games are ideal for short breaks between tasks or on mobile.',
      'Restarting instantly is part of the fun — don’t be afraid to retry quickly.',
    ],
    related: ['arcade', 'clicker'],
  },
  {
    id: 'puzzle',
    name: 'Puzzle',
    icon: '🧩',
    description: 'Free puzzle games online to sharpen your mind — logic, matching, and brain teasers playable instantly, no download.',
    why: 'Free online puzzle games are a great way to exercise logic and pattern recognition without any pressure — play at your own pace, right in the browser. From matching games to brain teasers, there’s no install and no login standing between you and the next level.',
    tips: [
      'Take your time — most puzzle games aren’t timed, so there’s no rush.',
      'Look for patterns before making a move rather than clicking randomly.',
      'If you get stuck, step away and come back — a fresh look often helps.',
    ],
    related: ['strategy', 'adventure'],
  },
  {
    id: 'racing',
    name: 'Racing',
    icon: '🏎️',
    description: 'Free racing games online — high-speed circuits, off-road rally, and karting action right in your browser.',
    why: 'Browser-based racing games deliver high-speed thrills without needing a console or a download — just pick a track and go. Whether it’s tight circuit racing or bumpy off-road rally action, free online racing games are built for instant replayability.',
    tips: [
      'Arrow keys or WASD are the standard controls unless stated otherwise on the game screen.',
      'Brake before sharp turns rather than mid-corner to keep control of your vehicle.',
      'Try a few laps first to learn the track before racing for best time.',
    ],
    related: ['sports', '2player'],
  },
  {
    id: 'sports',
    name: 'Sports',
    icon: '⚽',
    description: 'Free sports games online covering football, basketball, and more — instant browser gameplay, no download required.',
    why: 'Free online sports games let you compete in football, basketball, and other favorites without needing a console or a subscription. They’re quick to start, easy to learn, and perfect for a fast match whenever you have a few minutes to play.',
    tips: [
      'Check the control scheme shown on the game’s start screen before jumping in.',
      'Practice mode (if available) is a good way to learn timing before a real match.',
      'Many sports games support two players on one keyboard for local competition.',
    ],
    related: ['soccer', 'racing'],
  },
  {
    id: 'soccer',
    name: 'Soccer',
    icon: '🥅',
    description: 'Free soccer games online — score goals and compete instantly in your browser, no installs needed.',
    why: 'Free soccer games online bring quick matches, penalty shootouts, and arcade-style football action straight to your browser. No download, no team roster setup — just pick a game and start scoring goals right away.',
    tips: [
      'Time your shots rather than spamming the kick button for better accuracy.',
      'Use through-passes to break past defenders in games with full-team control.',
      'Penalty shootout modes are a great quick option when you’re short on time.',
    ],
    related: ['sports', 'multiplayer'],
  },
  {
    id: '2player',
    name: '2 Player',
    icon: '👥',
    description: 'Free 2 player games to play with a friend on the same device — instant browser gameplay, no download required.',
    why: 'Free 2 player games are built for sharing one screen and one keyboard with a friend — no second account, no download, just split controls and play head-to-head. They’re one of the easiest ways to turn a browser into a couch co-op setup.',
    tips: [
      'Check the control legend on screen — most 2 player games split the keyboard into two zones.',
      'Agree on controls before starting so both players know their keys.',
      'Best-of-three or best-of-five rounds make short 2 player games more competitive.',
    ],
    related: ['multiplayer', 'boys'],
  },
  {
    id: 'multiplayer',
    name: 'Multiplayer',
    icon: '🌐',
    description: 'Free multiplayer games online — compete or team up with other players instantly in your browser.',
    why: 'Free online multiplayer games connect you with other players instantly — no account creation, no download, just join and play. Whether you want to team up or go head-to-head, browser multiplayer games make it easy to compete with people in real time.',
    tips: [
      'A stable internet connection helps avoid lag during real-time multiplayer matches.',
      'Read the lobby or room rules before joining, since formats can vary by game.',
      'If a match is full, most games let you queue for the next round automatically.',
    ],
    related: ['2player', 'shooting'],
  },
  {
    id: 'shooting',
    name: 'Shooting',
    icon: '🎯',
    description: 'Free shooting games online — precision aim and action-packed combat playable instantly, no download.',
    why: 'Free shooting games test your aim and reaction time with fast, arcade-style combat you can play directly in the browser. From target practice to full combat missions, there’s no download needed to start shooting your way through the action.',
    tips: [
      'Mouse aiming is usually more precise than keyboard-only controls where available.',
      'Reload during lulls in combat rather than waiting until you’re out of ammo.',
      'Aim for headshots or weak points when the game rewards precision over spray.',
    ],
    related: ['action', 'multiplayer'],
  },
  {
    id: 'strategy',
    name: 'Strategy',
    icon: '♟️',
    description: 'Free strategy games online — plan, build, and outthink your opponents instantly in your browser.',
    why: 'Free online strategy games challenge you to plan ahead, manage resources, and outthink opponents rather than rely on reflexes. Playable directly in the browser, they’re perfect for players who prefer thoughtful, tactical gameplay over fast action.',
    tips: [
      'Scout or explore early before committing to a big strategy or build order.',
      'Balance resource gathering with defense so you’re not caught off guard.',
      'Pause to plan your next few moves rather than reacting turn by turn.',
    ],
    related: ['puzzle', 'clicker'],
  },
  {
    id: 'stickman',
    name: 'Stickman',
    icon: '🕴️',
    description: 'Free stickman games online — physics-based action and stick-figure mayhem playable instantly, no download.',
    why: 'Stickman games combine simple stick-figure visuals with often surprisingly deep physics-based combat and platforming. Free online stickman games are quick to load and easy to pick up, making them a favorite for fast, chaotic browser sessions.',
    tips: [
      'Physics-based movement can feel loose at first — a few practice rounds help a lot.',
      'Combo attacks often deal more damage than single hits in stickman fighting games.',
      'Ragdoll physics are part of the fun — don’t worry about looking clean, just win.',
    ],
    related: ['action', 'arcade'],
  },
  {
    id: 'clicker',
    name: 'Clicker',
    icon: '🖱️',
    description: 'Free clicker and idle games online — simple, addictive progression you can play instantly in your browser.',
    why: 'Free clicker and idle games are built around steady, satisfying progression — click, upgrade, and watch your numbers grow, even when you’re not actively playing. They’re easy to leave running in a browser tab while you check back on progress.',
    tips: [
      'Prioritize upgrades that boost your passive or idle income first.',
      'Leaving the tab open (where supported) lets idle progress continue in the background.',
      'Reinvest early earnings into multipliers rather than saving them up unused.',
    ],
    related: ['hypercasual', 'strategy'],
  },
  {
    id: 'cooking',
    name: 'Cooking',
    icon: '🍳',
    description: 'Free cooking games online — run a kitchen, serve customers, and master recipes instantly in your browser.',
    why: 'Free cooking games let you run a virtual kitchen, follow recipes, and serve a rush of customers — all without downloading a single app. They’re a relaxed, time-management style pick for players who enjoy multitasking under a friendly time limit.',
    tips: [
      'Prep ingredients ahead of a rush to avoid falling behind on orders.',
      'Watch cooking timers closely — burnt dishes usually cost more than a slow order.',
      'Upgrade kitchen stations when possible to speed up repeat recipes.',
    ],
    related: ['girls', 'puzzle'],
  },
  {
    id: 'girls',
    name: 'Girls',
    icon: '👗',
    description: 'Free girls games online — fashion, makeover, and creative games playable instantly, no download required.',
    why: 'Free girls games cover fashion design, makeovers, and creative dress-up play, all playable instantly in the browser with no install required. They’re a relaxed, creative pick when you want to design and customize rather than compete.',
    tips: [
      'Experiment with different combinations — most styling games let you redo choices freely.',
      'Check for daily or themed challenges that unlock extra outfits and items.',
      'Save or screenshot favorite looks if the game doesn’t have a gallery feature.',
    ],
    related: ['cooking', 'puzzle'],
  },
  {
    id: 'boys',
    name: 'Boys',
    icon: '👦',
    description: 'Free boys games online — action, sports, and competitive challenges playable instantly in your browser.',
    why: 'Free boys games bring together action, sports, and competitive challenges in one place — quick to load and easy to play instantly in the browser. It’s a solid starting point if you want a mix of genres without picking just one category.',
    tips: [
      'Browse by sub-genre (action, sports, racing) if you know what mood you’re in.',
      'Try a few different games — this category mixes genres more than most.',
      'Check New Games regularly, since fresh titles get added across all genres here.',
    ],
    related: ['action', 'sports'],
  },
]

// Backend games store the human category name (e.g. "2 Player"), not the url slug.
// Use this to build a correct category link/filter from a game's raw category field.
export function categoryForName(name) {
  if (!name) return CATEGORIES[0]
  const found = CATEGORIES.find(c => c.name.toLowerCase() === name.toLowerCase())
  return found || CATEGORIES[0]
}
