// Keyword-style search phrases people commonly use for free browser games,
// each pointing at the most relevant existing page. Anchor text intentionally
// varies (not just "{Category} Games") to cover more of the ways these are
// actually searched, e.g. "no download" / "online" / "free" variants.
export const POPULAR_SEARCHES = [
  { label: 'Free Online Games', href: '/' },
  { label: 'Play Free Games', href: '/' },
  { label: 'Free Games No Sign Up', href: '/' },
  { label: 'Browser Games Online', href: '/' },
  { label: 'Instant Play Games', href: '/' },
  { label: 'Free HTML5 Games Online', href: '/' },
  { label: 'Games You Can Play Instantly', href: '/' },
  { label: 'Free Games For PC Browser', href: '/' },
  { label: 'Play Games On Mobile Free', href: '/' },
  { label: 'New Online Games', href: '/new-games' },
  { label: 'Latest Free Games', href: '/new-games' },
  { label: 'Best Free Online Games', href: '/top-games' },
  { label: 'Top Rated Games Online', href: '/top-games' },
  { label: 'Free Games Blog & Guides', href: '/blog' },
  { label: 'How To Play Games Online', href: '/blog/play-games-without-downloading' },
  { label: 'Games Like Poki & CoolMath Games', href: '/games' },
  { label: 'Free Action Games Online', href: '/category/action' },
  { label: 'Action Games No Download', href: '/category/action' },
  { label: 'Free Adventure Games', href: '/category/adventure' },
  { label: 'Online Adventure Games', href: '/category/adventure' },
  { label: 'Classic Arcade Games Online', href: '/category/arcade' },
  { label: 'Free Arcade Games', href: '/category/arcade' },
  { label: 'Simple Online Games', href: '/category/hypercasual' },
  { label: 'Hypercasual Games Free', href: '/category/hypercasual' },
  { label: 'Free Puzzle Games Online', href: '/category/puzzle' },
  { label: 'Brain Games Online', href: '/category/puzzle' },
  { label: 'Free Racing Games Online', href: '/category/racing' },
  { label: 'Car Racing Games Online', href: '/category/racing' },
  { label: 'Free Sports Games Online', href: '/category/sports' },
  { label: 'Sports Games No Download', href: '/category/sports' },
  { label: 'Free Soccer Games Online', href: '/category/soccer' },
  { label: 'Football Games Online', href: '/category/soccer' },
  { label: '2 Player Games Online', href: '/category/2player' },
  { label: '2 Player Games No Download', href: '/category/2player' },
  { label: 'Free Multiplayer Games Online', href: '/category/multiplayer' },
  { label: 'Multiplayer Games No Download', href: '/category/multiplayer' },
  { label: 'Free Shooting Games Online', href: '/category/shooting' },
  { label: 'Shooter Games Online', href: '/category/shooting' },
  { label: 'Free Strategy Games Online', href: '/category/strategy' },
  { label: 'Strategy Games No Download', href: '/category/strategy' },
  { label: 'Free Stickman Games', href: '/category/stickman' },
  { label: 'Stickman Fighting Games', href: '/category/stickman' },
  { label: 'Free Clicker Games', href: '/category/clicker' },
  { label: 'Idle Games Online', href: '/category/clicker' },
  { label: 'Free Cooking Games Online', href: '/category/cooking' },
  { label: 'Restaurant Games Online', href: '/category/cooking' },
  { label: 'Free Girls Games Online', href: '/category/girls' },
  { label: 'Dress Up Games Online', href: '/category/girls' },
  { label: 'Free Boys Games Online', href: '/category/boys' },
  { label: 'Boys Games No Download', href: '/category/boys' },
]
